#App
spring.application.name=smartlead

# H2 Database
spring.datasource.url=jdbc:h2:mem:smartlead
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb.core=DEBUG

# HuggingFace (token goes in separate secrets file)
ai.huggingface.token=${HF_TOKEN}
